---
# Per environment values which override defaults in hmpps-person-record-manage-ui/values.yaml

generic-service:

  ingress:
    host: manage-person-record-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-person-record-preprod-cert-secret

  env:
    INGRESS_URL: "https://manage-person-record-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin-preprod.hmpps.service.justice.gov.uk'
    PERSON_RECORD_API_URL: "https://hmpps-person-record-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-person-record-alerts-prod
