---
# Per environment values which override defaults in hmpps-person-record-manage-ui/values.yaml

generic-service:

  ingress:
    host: hmpps-person-record-manage-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "http://localhost:3000"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin-preprod.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-person-record-alerts-prod
