---
# Per environment values which override defaults in hmpps-person-record-manage-ui/values.yaml

generic-service:

  ingress:
    host: manage-person-record-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-person-record-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin-dev.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-person-record-alerts-prod
